version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: docker/production/server/Dockerfile
    ports:
      - "8000:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  app:
    build:
      context: .
      dockerfile: docker/production/app/Dockerfile
    restart: always
    deploy:
      mode: global
      replicas: 1

  cron:
    build:
      context: .
      dockerfile: docker/production/app/Dockerfile
    command: "crond -f"
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
