version: "3.8"

services:
  fpm:
    image: iliashabanov/php:latest
    deploy:
      mode: replicated
      replicas: 1
    working_dir: /app
    volumes:
      - .:/app:rw

  cron:
    image: iliashabanov/php:latest
    command: "crond -f"
    deploy:
      mode: replicated
      replicas: 1
    working_dir: /app
    volumes:
      - .:/app:rw
      - ./docker/production/app/config/crontab:/var/spool/cron/crontabs/root:ro

  server:
    image: nginx:latest
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - .:/app:rw
      - ./docker/production/server/config:/etc/nginx/conf.d:ro

  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
