services:
    backend:
        build:
            context: .
            dockerfile: docker/local/backend/Dockerfile
        tty: true
        depends_on:
            - database
            - cache
        volumes:
            - .:/app
        ports:
            - "8000:8000"

    frontend:
        build:
            context: .
            dockerfile: docker/local/frontend/Dockerfile
        tty: true
        volumes:
            - .:/app
        ports:
            - "5173:5173"

    storage:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "8900:8900"
        environment:
            MINIO_ROOT_USER: 'ishabanov'
            MINIO_ROOT_PASSWORD: 'Vsz7kVb9HeoTH27s'
        volumes:
            - storage:/data:rw
        command: server /data --console-address ":8900"
        healthcheck:
            test: [ "CMD", "mc", "ready", "local" ]
            interval: 5s
            timeout: 5s
            retries: 5

    database:
        image: postgres:alpine
        environment:
            POSTGRES_DB: "ishabanov"
            POSTGRES_USER: "PxZ2"
            POSTGRES_PASSWORD: "Htmp2X"
        ports:
            - "5432:5432"
        volumes:
            - database:/var/lib/postgresql/data

    cache:
        image: redis:alpine
        ports:
            - "6379:6379"

volumes:
    database:
    storage:
