version: "3.8"

services:
  app:
    image: ${REGISTRY}/onepager/app:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8000:80"

  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
