name: Deploy Prod

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest

    environment: production

    needs:
      - tests
      - build

    steps:
      - name: Update Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          fingerprint: ${{ secrets.VPS_PRIVATE_FINGERPRINT }}
          port: 22
          script: |
            BUILD_VERION=${{ github.ref_name }} \
              docker stack deploy \
                --with-registry-auth \
                --compose-file ~/deploy/ishabanov/docker-compose.stage.yml \
                ishabanov_prod
