name: Deployment

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: 'Environment'
        required: true
        options:
          - production
          - staging

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Run PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: vendor/bin/phpunit

  release:
    runs-on: ubuntu-latest

    needs: tests

    steps:
      - uses: actions/checkout@master
      - uses: franzbischoff/replace_envs@v1
        env:
          GH_APP_KEY: ${{ secrets.APP_KEY_${{ github.event.inputs.destination }} }}
          GH_DATABASE: ${{ secrets.DATABASE_${{ github.event.inputs.destination }} }}
          GH_MAIL: ${{ secrets.MAIL_${{ github.event.inputs.destination }} }}
          GH_TELEGRAM: ${{ secrets.TELEGRAM_${{ github.event.inputs.destination }} }}
        with:
          from_file: '.env.${{ github.event.inputs.destination }}'
          to_file: '.env'
          commit: 'false'

      - name: "Build Frontend"
      - uses: actions/setup-node@v3
        with:
          node: 18.x
        run: npm install && npm run build && rm -rf ./node_modules

      - name: "Build Backend"
      - uses: php-actions/composer@v6
        with:
          php_version: '8.1'
        run: composer install --no-interaction --optimize-autoload --no-dev

      - name: "Upload"
      - uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
        with:
          source: "."
          target: "~/${{ github.event.repository.name }}"

      - name: "Deploy"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: cd ~/${{ github.event.repository.name }} && ./deploy/${{ github.event.inputs.destination }}/run.sh
