name: Deploy Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      tag: latest

  deploy:
    runs-on: ubuntu-latest

    environment: staging

    needs:
      - tests
      - build

    steps:
      - name: Update Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          fingerprint: ${{ secrets.VPS_PRIVATE_FINGERPRINT }}
          port: 22
          script: docker pull ghcr.io/liquidcats/ishabanov.com:latest

      - name: Update Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          fingerprint: ${{ secrets.VPS_PRIVATE_FINGERPRINT }}
          port: 22
          script: |
            BUILD_VERION=latest \
              docker stack deploy \
                --with-registry-auth \
                --compose-file ~/deploy/ishabanov/docker-compose.stage.yml \
                ishabanov_staging
